# Generated by Django 5.0.2 on 2025-06-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_alter_company_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(blank=True, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="company",
            name="country",
            field=models.CharField(blank=True, max_length=100, verbose_name="country"),
        ),
        migrations.AlterField(
            model_name="company",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="postal code"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="state",
            field=models.CharField(blank=True, max_length=100, verbose_name="state"),
        ),
    ]
